export const UPDATE_SEARCH_GLOBAL = "UPDATE_SEARCH_GLOBAL";
export const SET_SEARCH_GLOBAL = "SET_SEARCH_GLOBAL";
export const SET_HINTS_GLOBAL = "SET_HINTS_GLOBAL";
export const REFRESH_RECOMENDATION_PINS_GLOBAL = "REFRESH_RECOMENDATION_PINS_GLOBAL";
export const SET_RECOMENDATION_PINS_GLOBAL = "SET_RECOMENDATION_PINS_GLOBAL";
export const REFRESH_RECOMENDATION_HINTS_GLOBAL = "REFRESH_RECOMENDATION_HINTS_GLOBAL";
export const SET_RECOMENDATION_HINTS_GLOBAL = "SET_RECOMENDATION_HINTS_GLOBAL";
