export const UPDATE_SEARCH_GLOBAL = "UPDATE_SEARCH_GLOBAL";
export const SET_SEARCH_GLOBAL = "SET_SEARCH_GLOBAL";
export const SET_HINTS_GLOBAL = "SET_HINTS_GLOBAL";
export const REFRESH_RECOMENDATION_PINS = "REFRESH_RECOMENDATION_PINS";
export const SET_RECOMENDATION_PINS = "SET_RECOMENDATION_PINS";
export const SET_RECOMENDATION_HINTS = "SET_RECOMENDATION_HINTS";
