export const UPDATE_SEARCH_GLOBAL = "UPDATE_SEARCH_GLOBAL";
export const SET_SEARCH_GLOBAL = "SET_SEARCH_GLOBAL";
export const SET_HINTS_GLOBAL = "SET_HINTS_GLOBAL";

export const SET_BOOKMARK_STATE = "SET_BOOKMARK_STATE";

export const APPEND_HINTS_OBJECT_USER = "APPEND_HINTS_OBJECT_USER";
export const APPEND_HINTS_OBJECT_USER_SAVED = "APPEND_HINTS_OBJECT_USER_SAVED";
export const SPLICE_HINTS_OBJECT_USER_SAVED = "SPLICE_HINTS_OBJECT_USER_SAVED";

export const REFRESH_RECOMENDATION_PINS_GLOBAL = "REFRESH_RECOMENDATION_PINS_GLOBAL";
export const REFRESH_RECOMENDATION_PINS_USER = "REFRESH_RECOMENDATION_PINS_USER";
export const REFRESH_RECOMENDATION_PINS_USER_SAVED = "REFRESH_RECOMENDATION_PINS_USER_SAVED";

export const SET_RECOMENDATION_PINS_GLOBAL = "SET_RECOMENDATION_PINS_GLOBAL";
export const SET_RECOMENDATION_PINS_USER = "SET_RECOMENDATION_PINS_USER";
export const SET_RECOMENDATION_PINS_USER_SAVED = "SET_RECOMENDATION_PINS_USER_SAVED";

export const REFRESH_RECOMENDATION_HINTS_GLOBAL = "REFRESH_RECOMENDATION_HINTS_GLOBAL";
export const REFRESH_RECOMENDATION_HINTS_USER = "REFRESH_RECOMENDATION_HINTS_USER";
export const REFRESH_RECOMENDATION_HINTS_USER_SAVED = "REFRESH_RECOMENDATION_HINTS_USER_SAVED";

export const SET_RECOMENDATION_HINTS_GLOBAL = "SET_RECOMENDATION_HINTS_GLOBAL";
export const SET_RECOMENDATION_HINTS_USER = "SET_RECOMENDATION_HINTS_USER";
export const SET_RECOMENDATION_HINTS_USER_SAVED = "SET_RECOMENDATION_HINTS_USER_SAVED";

export const SET_SEARCH_DROPDOWN_TITLE = "SET_SEARCH_DROPDOWN_TITLE";

export const SET_CATEGORY_DROPDOWN_TITLE = "SET_CATEGORY_DROPDOWN_TITLE";
